# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches: 
      - master
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew buildPlugin
      
    - name: Verify against IntelliJ builds
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
      with:
        ide-versions: |
          ideaIC:2019.3.5
          ideaIU:2019.3.5
          ideaIC:2020.2.2
          ideaIU:2020.2.2
          ideaIC:LATEST-EAP-SNAPSHOT
          ideaIU:LATEST-EAP-SNAPSHOT
